#PYTHON data types
name = "joel ochieng"
print(name)
print(type(name))

#numeric
# int - this indicates a whole number. for an interger, we dont use quotes
age = 35
print('the age of a person is', age)
print(type(age))

#float

#addition
number = 20
number2 = 10
addition = number+number2
print("sum of numers is", addition)

#subtraction
number3 = 50
number4 = 15
difference = number3 - number4
print("the difference of the numbers is", difference)
#multiplication
number5 = 15
number6 = 6
product = number5 * number6
print("product of the numbers is", product)

#division
#number7 and number8

#modulus - this means the reminder of a number when get subdivided by another one
number9 = 14
number10 = 5
modulus = number9 % number10
print("the modules of the number is", modulus)

#FLOOR DIVISIONS - This is the number of times a number subdivides another ignoring the reminder
floor = number9 // number10

print("this is the floor, " floor)